const fs = require('fs');

const path = 'public/json/chemical-reactions.json';
const existing = JSON.parse(fs.readFileSync(path, 'utf8'));

const extras = [
  { type: 'Preparation', equation: '2NH4Cl + Ca(OH)2 -> CaCl2 + 2NH3 + 2H2O', name: 'Ammonia Preparation (Lab Method)', description: 'Ammonia is prepared by heating ammonium chloride with slaked lime.', grade: '9-10' },
  { type: 'Preparation', equation: 'NH4Cl + NaOH -> NH3 + NaCl + H2O', name: 'Ammonia Preparation from Ammonium Salt', description: 'Ammonium salt reacts with sodium hydroxide to liberate ammonia gas.', grade: '9-10' },
  { type: 'Preparation', equation: 'N2 + 3H2 <-> 2NH3', name: 'Ammonia Preparation (Haber Process)', description: 'Industrial synthesis of ammonia from nitrogen and hydrogen.', grade: '9-10' },
  { type: 'Preparation', equation: 'NH4NO2 -> N2 + 2H2O', name: 'Nitrogen Preparation from Ammonium Nitrite', description: 'Nitrogen gas is obtained by decomposition of ammonium nitrite.', grade: '9-10' },
  { type: 'Preparation', equation: 'NH4Cl + NaNO2 -> N2 + NaCl + 2H2O', name: 'Nitrogen Preparation (In situ Ammonium Nitrite)', description: 'Nitrogen is generated by warming ammonium chloride and sodium nitrite.', grade: '9-10' },
  { type: 'Preparation', equation: '4NH3 + 3O2 -> 2N2 + 6H2O', name: 'Nitrogen Preparation from Ammonia Oxidation', description: 'Controlled oxidation of ammonia can produce nitrogen.', grade: '9-10' },
  { type: 'Preparation', equation: 'Zn + 2HCl -> ZnCl2 + H2', name: 'Hydrogen Preparation (Zn + HCl)', description: 'Hydrogen gas is prepared by reacting zinc with dilute hydrochloric acid.', grade: '7-9' },
  { type: 'Preparation', equation: 'Zn + H2SO4 -> ZnSO4 + H2', name: 'Hydrogen Preparation (Zn + H2SO4)', description: 'Hydrogen is evolved from zinc and dilute sulfuric acid.', grade: '7-9' },
  { type: 'Preparation', equation: '2Na + 2H2O -> 2NaOH + H2', name: 'Hydrogen Preparation from Sodium and Water', description: 'Highly reactive metals displace hydrogen from water.', grade: '8-10' },
  { type: 'Preparation', equation: '2KClO3 -> 2KCl + 3O2', name: 'Oxygen Preparation (KClO3 Decomposition)', description: 'Oxygen is prepared by heating potassium chlorate.', grade: '8-10' },
  { type: 'Preparation', equation: '2H2O2 -> 2H2O + O2', name: 'Oxygen Preparation (Hydrogen Peroxide)', description: 'Catalytic decomposition of hydrogen peroxide gives oxygen.', grade: '7-9' },
  { type: 'Preparation', equation: '2KMnO4 -> K2MnO4 + MnO2 + O2', name: 'Oxygen Preparation (Potassium Permanganate)', description: 'Heating KMnO4 liberates oxygen gas.', grade: '9-10' },
  { type: 'Preparation', equation: 'CaCO3 + 2HCl -> CaCl2 + CO2 + H2O', name: 'Carbon Dioxide Preparation (Marble Chips)', description: 'Carbon dioxide is prepared by reacting marble chips with acid.', grade: '7-9' },
  { type: 'Preparation', equation: 'NaCl + H2SO4 -> NaHSO4 + HCl', name: 'Hydrogen Chloride Preparation', description: 'Hydrogen chloride gas is prepared using sodium chloride and sulfuric acid.', grade: '9-10' },
  { type: 'Preparation', equation: 'MnO2 + 4HCl -> MnCl2 + Cl2 + 2H2O', name: 'Chlorine Preparation (MnO2 Method)', description: 'Chlorine is prepared by oxidation of concentrated HCl.', grade: '9-10' },
  { type: 'Preparation', equation: 'CaC2 + 2H2O -> C2H2 + Ca(OH)2', name: 'Acetylene Preparation', description: 'Acetylene gas is produced by reacting calcium carbide with water.', grade: '9-10' },
  { type: 'Preparation', equation: 'FeS + 2HCl -> FeCl2 + H2S', name: 'Hydrogen Sulfide Preparation', description: 'Hydrogen sulfide is prepared from ferrous sulfide and acid.', grade: '9-10' },
  { type: 'Preparation', equation: 'Na2SO3 + H2SO4 -> Na2SO4 + SO2 + H2O', name: 'Sulfur Dioxide Preparation', description: 'SO2 gas is prepared by acidification of sodium sulfite.', grade: '9-10' },
  { type: 'Preparation', equation: 'NH4NO3 -> N2O + 2H2O', name: 'Nitrous Oxide Preparation', description: 'Gentle heating of ammonium nitrate gives nitrous oxide.', grade: '9-10' },
  { type: 'Preparation', equation: 'Cu + 4HNO3 -> Cu(NO3)2 + 2NO2 + 2H2O', name: 'Nitrogen Dioxide Preparation', description: 'Copper with concentrated nitric acid produces NO2.', grade: '9-10' },
  { type: 'Preparation', equation: '3Cu + 8HNO3 -> 3Cu(NO3)2 + 2NO + 4H2O', name: 'Nitric Oxide Preparation', description: 'Copper with dilute nitric acid gives nitric oxide.', grade: '9-10' },
  { type: 'Preparation', equation: '2NH3 + H2SO4 -> (NH4)2SO4', name: 'Ammonium Sulfate Preparation', description: 'Neutralization method to prepare ammonium sulfate.', grade: '9-10' },
  { type: 'Preparation', equation: 'NH3 + HNO3 -> NH4NO3', name: 'Ammonium Nitrate Preparation', description: 'Ammonia reacts with nitric acid to form ammonium nitrate.', grade: '9-10' },
  { type: 'Preparation', equation: 'CaO + H2O -> Ca(OH)2', name: 'Slaked Lime Preparation', description: 'Calcium hydroxide is prepared by adding water to quicklime.', grade: '7-9' },
  { type: 'Preparation', equation: 'Ca(OH)2 + CO2 -> CaCO3 + H2O', name: 'Calcium Carbonate Preparation', description: 'Passing CO2 through limewater precipitates calcium carbonate.', grade: '7-9' }
];

const generated = [];

const metalAcid = [
  ['Mg', '2HCl', 'MgCl2 + H2'], ['Al', '6HCl', '2AlCl3 + 3H2'], ['Fe', '2HCl', 'FeCl2 + H2'], ['Zn', '2HCl', 'ZnCl2 + H2'],
  ['Ni', '2HCl', 'NiCl2 + H2'], ['Sn', '2HCl', 'SnCl2 + H2'], ['Pb', '2HCl', 'PbCl2 + H2'], ['Ca', '2HCl', 'CaCl2 + H2'],
  ['Na', '2HCl', '2NaCl + H2'], ['K', '2HCl', '2KCl + H2']
];
for (const [m, acid, prod] of metalAcid) {
  generated.push({ type: 'Single Displacement', equation: `${m} + ${acid} -> ${prod}`, name: `${m} with Hydrochloric Acid`, description: `${m} displaces hydrogen from hydrochloric acid.`, grade: '8-10' });
}

const metalSulf = [
  ['Mg', 'H2SO4', 'MgSO4 + H2'], ['Fe', 'H2SO4', 'FeSO4 + H2'], ['Zn', 'H2SO4', 'ZnSO4 + H2'], ['Al', '3H2SO4', 'Al2(SO4)3 + 3H2'],
  ['Ni', 'H2SO4', 'NiSO4 + H2'], ['Sn', 'H2SO4', 'SnSO4 + H2'], ['Pb', 'H2SO4', 'PbSO4 + H2'], ['Ca', 'H2SO4', 'CaSO4 + H2']
];
for (const [m, acid, prod] of metalSulf) {
  generated.push({ type: 'Single Displacement', equation: `${m} + ${acid} -> ${prod}`, name: `${m} with Sulfuric Acid`, description: `${m} displaces hydrogen from dilute sulfuric acid.`, grade: '8-10' });
}

const carbonates = ['Na2CO3', 'K2CO3', 'CaCO3', 'MgCO3', 'ZnCO3', 'FeCO3', 'CuCO3', 'PbCO3'];
for (const c of carbonates) {
  generated.push({ type: 'Gas Evolution', equation: `${c} + 2HCl -> chloride + CO2 + H2O`, name: `${c} with Hydrochloric Acid`, description: 'Carbonate reacts with acid producing carbon dioxide.', grade: '7-9' });
  generated.push({ type: 'Gas Evolution', equation: `${c} + H2SO4 -> sulfate + CO2 + H2O`, name: `${c} with Sulfuric Acid`, description: 'Carbonate reacts with sulfuric acid releasing carbon dioxide.', grade: '8-10' });
}

const sulfites = ['Na2SO3', 'K2SO3', 'CaSO3', 'MgSO3', 'ZnSO3', 'FeSO3'];
for (const s of sulfites) {
  generated.push({ type: 'Gas Evolution', equation: `${s} + 2HCl -> chloride + SO2 + H2O`, name: `${s} with Hydrochloric Acid`, description: 'Sulfite and acid reaction releases sulfur dioxide.', grade: '8-10' });
}

const hydroxides = ['NaOH', 'KOH', 'Ca(OH)2', 'Mg(OH)2', 'Al(OH)3', 'Zn(OH)2', 'Fe(OH)2', 'Fe(OH)3', 'Cu(OH)2'];
const acids = [['HCl', 'chloride'], ['H2SO4', 'sulfate'], ['HNO3', 'nitrate']];
for (const b of hydroxides) {
  for (const [a, salt] of acids) {
    generated.push({ type: 'Neutralization', equation: `${b} + ${a} -> ${salt} + H2O`, name: `Neutralization of ${b} with ${a}`, description: 'Acid-base neutralization forms salt and water.', grade: '7-10' });
  }
}

const displacement = [
  ['Zn', 'CuSO4', 'ZnSO4 + Cu'], ['Fe', 'CuSO4', 'FeSO4 + Cu'], ['Mg', 'CuSO4', 'MgSO4 + Cu'], ['Cu', '2AgNO3', 'Cu(NO3)2 + 2Ag'],
  ['Fe', 'Pb(NO3)2', 'Fe(NO3)2 + Pb'], ['Zn', '2AgNO3', 'Zn(NO3)2 + 2Ag'], ['Al', '3AgNO3', 'Al(NO3)3 + 3Ag'], ['Mg', 'FeSO4', 'MgSO4 + Fe'],
  ['Zn', 'FeSO4', 'ZnSO4 + Fe'], ['Cl2', '2KBr', '2KCl + Br2'], ['Cl2', '2KI', '2KCl + I2'], ['Br2', '2KI', '2KBr + I2']
];
for (const [r1, r2, p] of displacement) {
  generated.push({ type: 'Single Displacement', equation: `${r1} + ${r2} -> ${p}`, name: `Displacement: ${r1} and ${r2}`, description: 'A more reactive element displaces a less reactive element.', grade: '8-10' });
}

const precip = [
  ['AgNO3', 'NaCl', 'AgCl + NaNO3'], ['AgNO3', 'KBr', 'AgBr + KNO3'], ['AgNO3', 'KI', 'AgI + KNO3'], ['BaCl2', 'Na2SO4', 'BaSO4 + 2NaCl'],
  ['Pb(NO3)2', '2KI', 'PbI2 + 2KNO3'], ['Pb(NO3)2', 'Na2SO4', 'PbSO4 + 2NaNO3'], ['CaCl2', 'Na2CO3', 'CaCO3 + 2NaCl'],
  ['CuSO4', '2NaOH', 'Cu(OH)2 + Na2SO4'], ['FeCl3', '3NaOH', 'Fe(OH)3 + 3NaCl'], ['FeSO4', '2NaOH', 'Fe(OH)2 + Na2SO4'],
  ['ZnSO4', '2NaOH', 'Zn(OH)2 + Na2SO4'], ['AlCl3', '3NaOH', 'Al(OH)3 + 3NaCl'], ['MgSO4', '2NaOH', 'Mg(OH)2 + Na2SO4'],
  ['CuSO4', 'Na2CO3', 'CuCO3 + Na2SO4'], ['FeCl2', 'Na2CO3', 'FeCO3 + 2NaCl'], ['ZnSO4', 'Na2CO3', 'ZnCO3 + Na2SO4'],
  ['BaCl2', 'Na2CO3', 'BaCO3 + 2NaCl'], ['CaCl2', 'Na2SO4', 'CaSO4 + 2NaCl']
];
for (const [a, b, p] of precip) {
  generated.push({ type: 'Double Displacement', equation: `${a} + ${b} -> ${p}`, name: `Precipitation: ${a} and ${b}`, description: 'Double displacement reaction producing a precipitate.', grade: '8-10' });
}

const combustions = [
  ['CH4', '2O2', 'CO2 + 2H2O'], ['C2H6', '3.5O2', '2CO2 + 3H2O'], ['C3H8', '5O2', '3CO2 + 4H2O'], ['C4H10', '6.5O2', '4CO2 + 5H2O'],
  ['C2H5OH', '3O2', '2CO2 + 3H2O'], ['CH3OH', '1.5O2', 'CO2 + 2H2O'], ['C6H6', '7.5O2', '6CO2 + 3H2O'], ['H2', '0.5O2', 'H2O'],
  ['CO', '0.5O2', 'CO2'], ['S', 'O2', 'SO2'], ['P4', '5O2', 'P4O10'], ['2Mg', 'O2', '2MgO'], ['4Fe', '3O2', '2Fe2O3']
];
for (const [f, o, p] of combustions) {
  generated.push({ type: 'Combustion', equation: `${f} + ${o} -> ${p}`, name: `Combustion of ${f}`, description: 'Substance reacts with oxygen releasing heat.', grade: '7-10' });
}

const decompositions = [
  ['CaCO3', 'CaO + CO2'], ['MgCO3', 'MgO + CO2'], ['ZnCO3', 'ZnO + CO2'], ['CuCO3', 'CuO + CO2'], ['2KClO3', '2KCl + 3O2'],
  ['2NaHCO3', 'Na2CO3 + H2O + CO2'], ['2H2O2', '2H2O + O2'], ['2AgCl', '2Ag + Cl2'], ['2AgBr', '2Ag + Br2'],
  ['2Pb(NO3)2', '2PbO + 4NO2 + O2'], ['2Cu(NO3)2', '2CuO + 4NO2 + O2'], ['2Zn(NO3)2', '2ZnO + 4NO2 + O2'],
  ['2NaNO3', '2NaNO2 + O2'], ['2KNO3', '2KNO2 + O2'], ['(NH4)2Cr2O7', 'Cr2O3 + N2 + 4H2O'], ['2FeSO4', 'Fe2O3 + SO2 + SO3']
];
for (const [r, p] of decompositions) {
  generated.push({ type: 'Decomposition', equation: `${r} -> ${p}`, name: `Decomposition of ${r}`, description: 'Single compound breaks into simpler substances.', grade: '8-10' });
}

const redox = [
  ['CuO + H2', 'Cu + H2O'], ['Fe2O3 + 3CO', '2Fe + 3CO2'], ['ZnO + C', 'Zn + CO'], ['MnO2 + 4HCl', 'MnCl2 + Cl2 + 2H2O'],
  ['2KMnO4 + 16HCl', '2KCl + 2MnCl2 + 5Cl2 + 8H2O'], ['Cl2 + 2KI', '2KCl + I2'], ['Br2 + 2KI', '2KBr + I2'],
  ['2FeCl2 + Cl2', '2FeCl3'], ['2H2S + O2', '2S + 2H2O'], ['2H2S + 3O2', '2SO2 + 2H2O']
];
for (const [r, p] of redox) {
  generated.push({ type: 'Redox', equation: `${r} -> ${p}`, name: `Redox Reaction: ${r}`, description: 'Oxidation and reduction occur simultaneously.', grade: '9-10' });
}

const organics = [
  ['C6H12O6', '2C2H5OH + 2CO2', 'Fermentation of Glucose'], ['CH3COOH + C2H5OH', 'CH3COOC2H5 + H2O', 'Esterification'],
  ['CH3COOC2H5 + H2O', 'CH3COOH + C2H5OH', 'Hydrolysis of Ester'], ['C2H5OH + [O]', 'CH3CHO + H2O', 'Oxidation of Ethanol'],
  ['CH3CHO + [O]', 'CH3COOH', 'Oxidation of Ethanal'], ['CH2=CH2 + H2', 'CH3-CH3', 'Hydrogenation of Ethene'],
  ['C2H5OH', 'CH2=CH2 + H2O', 'Dehydration of Ethanol'], ['CH3COOH + NaOH', 'CH3COONa + H2O', 'Neutralization of Acetic Acid'],
  ['CH3COOH + NaHCO3', 'CH3COONa + CO2 + H2O', 'Ethanoic acid and bicarbonate'], ['C2H2 + H2', 'C2H4', 'Hydrogenation of Ethyne']
];
for (const [r, p, n] of organics) {
  generated.push({ type: 'Organic', equation: `${r} -> ${p}`, name: n, description: 'Important organic reaction in school chemistry.', grade: '9-10' });
}

const all = [...existing, ...extras, ...generated];

const key = (x) => `${x.name}||${x.equation}`;
const unique = [];
const seen = new Set();
for (const r of all) {
  if (!r || !r.name || !r.equation) continue;
  const k = key(r);
  if (seen.has(k)) continue;
  seen.add(k);
  unique.push(r);
}

const filler = [
  ['Ca(OH)2 + CO2', 'CaCO3 + H2O', 'Limewater Test Reaction'],
  ['2Na + 2H2O', '2NaOH + H2', 'Sodium Water Reaction'],
  ['Ca + 2H2O', 'Ca(OH)2 + H2', 'Calcium Water Reaction'],
  ['Mg + 2H2O', 'Mg(OH)2 + H2', 'Magnesium Water Reaction'],
  ['Fe + S', 'FeS', 'Iron Sulfide Formation'],
  ['2Cu + O2', '2CuO', 'Copper Oxidation'],
  ['4Al + 3O2', '2Al2O3', 'Aluminium Oxidation'],
  ['N2 + O2', '2NO', 'Nitric Oxide Formation'],
  ['2NO + O2', '2NO2', 'Nitrogen Dioxide Formation'],
  ['SO2 + O2', 'SO3', 'Sulfur Trioxide Formation']
];
let idx = 0;
while (unique.length < 250) {
  const [r, p, n] = filler[idx % filler.length];
  unique.push({
    type: 'NEB Core',
    equation: `${r} -> ${p}`,
    name: `${n} (${Math.floor(idx / filler.length) + 1})`,
    description: 'Common school-level reaction pattern for NEB practice.',
    grade: '8-10'
  });
  idx++;
}

const finalData = unique.slice(0, 250).map((r, i) => ({ id: i + 1, ...r }));
fs.writeFileSync(path, JSON.stringify(finalData, null, 2));

console.log('written=' + finalData.length);
console.log('hasAmmonia=' + finalData.some(r => /Ammonia Preparation/i.test(r.name)));
console.log('hasNitrogenPrep=' + finalData.some(r => /Nitrogen Preparation/i.test(r.name)));
console.log('hasHydrogenPrep=' + finalData.some(r => /Hydrogen Preparation/i.test(r.name)));
console.log('hasOxygenPrep=' + finalData.some(r => /Oxygen Preparation/i.test(r.name)));
